name: Deploy Website to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

     
      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts

     
      - name: Upload Files to EC2
        uses: easingthemes/ssh-deploy@v3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          SOURCE: "./"
          ARGS: "-avz"

    
      - name: Execute Commands on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install apache2 -y
            sudo systemctl enable apache2
            sudo systemctl start apache2
            
            sudo mkdir -p /var/www/html
            sudo cp -r /home/ubuntu/website/* /var/www/html/
            
            sudo systemctl restart apache2
